- package-lock.json
- package.json
* chore: install react router dom
* chore: install react hook form and zod
* chore: install redux toolkit
> chore: add dependencies (#1)

- package-lock.json
- package.json
- src/app/config/firebase.ts
* chore: install firebase
* chore: config firebase
> chore: add and configure firebase (#3)

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .github/dependabot.yml
- vite.config.ts
* chore: add dev container
* chore: change server port
* chore: add dependabot config
> chore: add and config dev container (#5)

- .devcontainer/devcontainer.json
- vite.config.ts
* fix: add vite host option
* fix: expose port in dev container
> fix: dev containers (#7)

- src/App.tsx
- src/app/app.tsx
- src/app/router/router.tsx
- src/main.tsx
* feat: add router
* feat: add router config
> feat: add navigation (#9)

- src/app/app.tsx
- src/components/mode-toggle.tsx
- src/components/theme-provider.tsx
- src/components/ui/dropdown-menu.tsx
* feat: add theme provider
* feat: add dropdown component
* feat: add theme toggle component
* feat: add theme provider wrapper
> feat: add theme provider (#11)

- src/app/router/router.tsx
- src/components/event-card.tsx
- src/components/events-dashboard.tsx
- src/components/ui/calendar.tsx
- src/components/ui/card.tsx
- src/components/ui/input.tsx
* fear: add card component
* feat: add calendar component
* feat: add input component
* feat: add event-card
* feat: add event dashboard (wip)
* feat: add event dashboard route
> feat: add event dashboard (#17)

- src/app/store/generic-slice.ts
- src/app/store/store.ts
- src/main.tsx
* feat: add redux store
* feat: add generic slice
* feat: add redux provider wrapper
> feat: add redux toolkit (#21)

- components.json
- eslint.config.js
- package-lock.json
- package.json
- src/app/hooks/use-toast.ts
- src/components/ui/toast.tsx
- src/components/ui/toaster.tsx
- src/main.tsx
* chore: install toaster
* feat: add toast hook
* feat: add tosater components
* refactor: change libs folder path
* chore: config eslint
> feat: add toaster (#23)

- src/app/hooks/firestore/get-query.ts
- src/app/hooks/firestore/types.ts
- src/app/hooks/firestore/use-firestore.ts
* feat: add firestore hook types
* feat: add get query helper
* feat: add firestore hook
> feat: add firestore hook (#25)

- package-lock.json
- package.json
- src/app/app.tsx
- src/app/config/firebase.ts
- src/app/hooks/firestore/use-firestore.ts
- src/app/layouts/main-layout.tsx
- src/app/layouts/nav/main-nav.tsx
- src/app/router/router.tsx
- src/app/store/store.ts
- src/app/types/user.ts
- src/components/ui/input.tsx
- src/components/ui/label.tsx
- src/features/auth/auth-slice.ts
- src/features/auth/components/social-login.tsx
- src/features/auth/login/components/login-form.tsx
- src/features/auth/login/login-page.tsx
- src/features/auth/register/components/register-form.tsx
- src/features/auth/register/register-page.tsx
* feat: add label component
* feat: add icon and error msgs to input component
* feat: add auth slice
* feat: add auth to firebase config
* feat: add auth state listener
* style: add danger styles and better msg to toasts
* feat: adjust layout and nav to accommodate auth
* feat: add user type
* feat: add social login component
* feat: add login page and form
* feat: add register page and form
* feat: add auth pages to the router
> feat: add auth and it's components and configs (#27)

- package-lock.json
- package.json
Added the following dependencies:
* @googlemaps/react-wrapper
* @types/google.maps
* @radix-ui/react-popover"
* @radix-ui/react-select
* react-loader-spinner
* use-places-autocomplete
> chore: add new dependencies

- package-lock.json
- package.json
Added the following dependencies:
@googlemaps/react-wrapper
@types/google.maps
@radix-ui/react-popover"
@radix-ui/react-select
react-loader-spinner
use-places-autocomplete
> chore: add new dependencies (#29)

- package-lock.json
- package.json
> chrore: add dependency

- package-lock.json
- package.json
> chrore: add dependency (#34)

- src/components/ui/command.tsx
- src/components/ui/dialog.tsx
- src/components/ui/skeleton.tsx
Adds:
* command
* dialog
* sekeleton
components.
> feat: add new ui components

- src/components/ui/command.tsx
- src/components/ui/dialog.tsx
- src/components/ui/skeleton.tsx
Adds:
* command
* dialog
* sekeleton
components.
> feat: add new ui components (#36)

- index.html
- src/features/auth/components/social-login.tsx
* [feat: removed the inicial loader](https://github.com/genesluna/event-driven/commit/8ea83d719fa0394ba012812971498ec9b3648c34)
* [fix: removed log](https://github.com/genesluna/event-driven/commit/95f9744af776a64ccc1c6fd971da00951549bc25)
> feat: removed the inicial loader

- package-lock.json
- package.json
- src/app/layouts/nav/main-nav.tsx
- src/components/ui/accordion.tsx
- src/components/ui/avatar.tsx
- src/components/ui/badge.tsx
* chore: add dependencies
* feat: add avatar component
* feat: add badge component
* feat: add accordion component
* feat: use avatar component
> feat: add new compponents (#65)

- src/app/lib/utils.ts
- src/components/ui/button.tsx
- src/features/auth/components/social-login.tsx
- src/features/events/dashboard/components/event-card.tsx
- src/features/events/dashboard/components/event-filters.tsx
- src/styles/styles.css
* style: change some styles
* feat: add new helper functions
> style: change some styles and add helper functions (#68)

- src/features/events/details/components/event-details-card.tsx
- src/features/events/details/components/event-details-comments-form.tsx
- src/features/events/details/components/event-details-comments.tsx
- src/features/events/details/components/event-details-map.tsx
- src/features/events/details/components/event-details-sidebar.tsx
- src/features/events/details/event-details-page.tsx
* feat: add event details page
* feat: add event details card
* feat: add event details comments form
* feat: add event details comments
* feat: add event details map
* feat: add event details sidebar
> feat: add envent details (#70)

- package-lock.json
- package.json
- src/app/types/event.ts
- src/components/image-cropper.tsx
- src/components/image-modal.tsx
- src/features/events/dashboard/components/event-card.tsx
- src/features/events/details/components/event-details-card.tsx
* chore: add depencencies
* feat: add coverImgURL field
* feat: add image cropper
* feat: add image update and crop modal
* feat: add image loading
* feat: adjust displayed cover image
* fix: remove wrong css import
> feat: manage event image (#77)

- src/app/types/event.ts
- src/components/comments.tsx
- src/features/events/details/event-details-page.tsx
* refactor: changed type name
* feat: add comments moderation, deletion and permission rules.
* refactor: now passing down the event instead of the id.
> feat: add comments moderation and permissions (#86)

- src/app/layouts/nav/main-nav.tsx
- src/app/router/router.tsx
- src/features/events/dashboard/components/event-card.tsx
- src/features/events/details/components/event-details-card.tsx
- src/features/events/details/components/event-details-sidebar.tsx
- src/features/profiles/components/profile-feed-events-list.tsx
- src/features/profiles/components/profile-feed.tsx
- src/features/profiles/components/profile-info.tsx
- src/features/profiles/profile-page.tsx
* feat: add profile info component
* feat: add profile events list component
* feat: add frolifes feed componet
* feat: add profile page
* feat: add profile page navigations
* feat: add auth guard and proflle page routing
* style: change button disable style
> feat: add profile page (#89)

- src/app/types/profile.ts
- src/features/profiles/components/profile-edit.tsx
- src/features/profiles/components/profile-info.tsx
- src/features/profiles/profile-page.tsx
* feat: add website field
* feat: add profile page
* feat: add profile edit
* feat: add profile info
> feat: add profile (#102)

- firebase.json
- functions/.eslintrc.js
- functions/.gitignore
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/src/types/event.ts
- functions/tsconfig.dev.json
- functions/tsconfig.json
- tsconfig.json
Adds firebase functions to the project and [adds event write trigger function to create newsfeed](https://github.com/genesluna/event-driven/commit/4a89fda2acd34a4d895a4e4b3f4ffbcfa293de63)
> feat: add firebase functions

- firebase.json
- functions/.eslintrc.js
- functions/.gitignore
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/src/types/event.ts
- functions/tsconfig.dev.json
- functions/tsconfig.json
- tsconfig.json
* feat: add firebase functions
* feat: add event write trigger function to create newsfeed
> feat: add firebase functions (#105)
